### ISSUE TITLE
Config.yml

### ISSUE THREAD

**Issue by Yann151924** [KasperFranz/ItemRestrict#1]
Linked to your response here :) : https://github.com/brunyman/ItemRestrict/issues/1

I think the config can be much easier and clearly much simple to write, if you remove the part with "Messages" and handle the reason in same line where you declare the banned item.
This is an example : 7:*:Bedrock:I want to ban it

Personnaly i prefer this approach it's much simple and you don't repeat the id/name three times in file.

**Comment by KasperFranz** [comment]
I can see what you mean

a solution would be to do something like this: 

``` bans:
    Bedrock:  
        type:  
          placement: true  
          usage: true  
        Label: bedrock  
        Message: I Want to ban it  
```

Where the type can bethe 5 different types (usage,placement,crafting,equip,ownership)

What do you think about this idéa?

**Comment by Yann151924** [comment]
That can be good, but what is the label for you ?

```
Bedrock:  <- can be the bukkit api name ?
    type:  
      placement: true  
      usage: true  
    Label: bedrock  
    Message: I Want to ban it  
```
